# Generated by Django 5.0 on 2023-12-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_departamentos_funcionario_empresa_and_more'),
        ('registo_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registohoraextra',
            old_name='nome',
            new_name='motivo',
        ),
        migrations.AddField(
            model_name='registohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
