# Generated by Django 5.0.1 on 2024-01-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_departamentos_funcionario_empresa_and_more'),
        ('registo_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registohoraexta',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
