# Generated by Django 5.0.1 on 2024-01-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='name',
            new_name='nome',
        ),
    ]
